apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: registry:latest
          ports:
            - containerPort: 5000
          env:
            - name: REGISTRY_AUTH
              value: "htpasswd"
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: "Registry Realm"
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: "/auth/htpasswd"
            - name: REGISTRY_HTTP_SECRET
              valueFrom:
                secretKeyRef:
                  name: registry-http-secret
                  key: http-secret
          volumeMounts:
            - name: registry-storage
              mountPath: /var/lib/registry
            - name: auth-volume
              mountPath: /auth
      volumes:
        - name: registry-storage
          emptyDir: {}
        - name: auth-volume
          secret:
            secretName: registry-auth-secret
